<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<a href="/posts/new">Новый пост</a>

<!-- BEGIN -->
<ul>
    <?php foreach ($posts as $post): ?>
        <li>
            <?= htmlspecialchars($post['name']) ?>
            <form action="/posts/<?= $post['id'] ?>" method="post" style="display:inline;">
                <input type="hidden" name="_METHOD" value="DELETE">
                <button type="submit">Delete</button>
            </form>
        </li>
    <?php endforeach; ?>
</ul>
<!-- END -->
